<div class="row pt-4 mb-3 align-items-center">
    <div class="col-md-6">
        <h2 class="text-warning text-dark-emphasis mb-0"><i class="bi bi-cpu-fill text-warning me-2"></i> System
            Analytics Tracker</h2>
        <p class="text-muted fw-bold">Live API auditing layer — Restricted to Super Admins</p>
    </div>
    <div class="col-md-6 text-md-end">
        <button id="btnRunCron" class="btn btn-warning shadow-sm rounded border-3 me-2 fw-bold text-dark"><i
                class="bi bi-gear-wide-connected me-1"></i> Trigger Scheduled Tasks</button>
        <a href="/dashboard" class="btn btn-outline-secondary ms-2 shadow-sm rounded border-3">Exit
            Developer Station</a>
    </div>
</div>

<!-- Add simple terminal output modal/hook for JS injection later -->
<div id="cronOutputAlert"
    class="alert alert-dark font-monospace small d-none shadow-sm rounded-3 mt-3 mb-4 border border-secondary"
    style="white-space: pre-wrap; max-height: 250px; overflow-y: auto;"></div>

<div class="row mb-5 g-4 mt-2">
    <!-- Prompt Tokens Metric block -->
    <div class="col-md-6 col-lg-4">
        <div class="card border-0 shadow-sm h-100 bg-white">
            <div class="card-body p-4 d-flex align-items-center">
                <div class="p-3 bg-light text-warning rounded-circle me-4 shadow-sm border border-warning">
                    <i class="bi bi-upload fs-2"></i>
                </div>
                <div>
                    <h5 class="card-title text-muted mb-1 fw-bold text-uppercase"
                        style="letter-spacing: 0.5px; font-size: 0.8rem;">Platform Uploaded Logic</h5>
                    <h2 class="mb-0 text-dark fw-bolder">
                        <?= number_format($data['token_aggregations']['total_pt'] ?? 0); ?> <span
                            class="fs-6 fw-normal text-muted">Tokens</span>
                    </h2>
                </div>
            </div>
            <div class="card-footer bg-light border-0 py-2">
                <small class="text-muted"><i class="bi bi-info-circle pe-1"></i> Data sent from our server to the
                    AI.</small>
            </div>
        </div>
    </div>

    <!-- Completion Tokens Metric block -->
    <div class="col-md-6 col-lg-4">
        <div class="card border-0 shadow-sm h-100 bg-white">
            <div class="card-body p-4 d-flex align-items-center">
                <div class="p-3 bg-light text-success rounded-circle me-4 shadow-sm border border-success">
                    <i class="bi bi-download fs-2"></i>
                </div>
                <div>
                    <h5 class="card-title text-muted mb-1 fw-bold text-uppercase"
                        style="letter-spacing: 0.5px; font-size: 0.8rem;">Returned Gen-AI Answers</h5>
                    <h2 class="mb-0 text-dark fw-bolder">
                        <?= number_format($data['token_aggregations']['total_ct'] ?? 0); ?> <span
                            class="fs-6 fw-normal text-muted">Tokens</span>
                    </h2>
                </div>
            </div>
            <div class="card-footer bg-light border-0 py-2">
                <small class="text-muted"><i class="bi bi-info-circle pe-1"></i> Words actually generated by Groq /
                    OpenAI.</small>
            </div>
        </div>
    </div>

    <!-- Active Models block -->
    <div class="col-md-6 col-lg-4">
        <div class="card border-0 shadow-sm h-100 bg-dark">
            <div class="card-body p-4 d-flex align-items-center">
                <div class="p-3 bg-secondary text-white rounded-circle me-4 shadow-sm">
                    <i class="bi bi-lightning-charge-fill fs-2 text-warning"></i>
                </div>
                <div>
                    <h5 class="card-title text-white opacity-50 mb-1 fw-bold text-uppercase"
                        style="letter-spacing: 0.5px; font-size: 0.8rem;">Active Intelligence Vector</h5>
                    <h3 class="mb-0 text-white fw-bolder">
                        <?= htmlspecialchars(strtoupper((new Setting())->getSetting('ai_provider'))); ?> <span
                            class="fs-6 fw-normal opacity-50">Enabled</span>
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="card shadow-sm border-0 border-top border-warning border-4 rounded-3 h-100 mb-5">
    <div
        class="card-header bg-white border-bottom-0 pb-0 pt-4 px-4 d-flex justify-content-between align-items-center mb-2">
        <h4 class="mb-0 text-dark fw-bold">Live API Request Logs</h4>
        <div class="badge bg-warning text-dark p-2 border border-warning shadow-sm"><i class="bi bi-wifi pe-1"></i>
            Stream</div>
    </div>

    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="bg-light text-secondary text-uppercase small" style="border-top: 2px solid #eaeaea;">
                    <tr>
                        <th class="ps-4 py-3">Timestamp</th>
                        <th class="py-3">Administrator Logged</th>
                        <th class="py-3">Remote Endpoint Pinged</th>
                        <th class="text-end py-3">Tokens Out</th>
                        <th class="text-end pe-4 py-3">Tokens Back</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($data['ai_logs'])): ?>
                        <tr>
                            <td colspan="5" class="text-center py-5 text-muted">
                                <i class="bi bi-shield-slash fs-2 d-block mb-3 text-secondary opacity-25"></i>
                                No AI tokens have been burned by the system yet.
                            </td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($data['ai_logs'] as $log): ?>
                            <tr>
                                <td class="ps-4 font-monospace small text-muted">
                                    <i class="bi bi-clock-history me-1"></i>
                                    <?= date('Y-m-d H:i:s', strtotime($log['created_at'])); ?>
                                </td>
                                <td>
                                    <?php if ($log['full_name']): ?>
                                        <div class="d-flex align-items-center">
                                            <div class="bg-primary bg-opacity-10 text-primary fw-bold rounded-circle d-flex align-items-center justify-content-center me-2"
                                                style="width: 32px; height: 32px; font-size: 13px;">
                                                <?= strtoupper(substr($log['full_name'], 0, 1)); ?>
                                            </div>
                                            <span class="text-dark fw-bold">
                                                <?= htmlspecialchars($log['full_name']); ?>
                                            </span>
                                        </div>
                                    <?php else: ?>
                                        <span class="text-muted fst-italic">System Core</span>
                                    <?php endif; ?>
                                </td>
                                <td><span
                                        class="badge bg-light text-dark border border-secondary shadow-sm font-monospace text-truncate d-inline-block"
                                        style="max-width: 250px;">
                                        <?= htmlspecialchars($log['endpoint']); ?>
                                    </span></td>
                                <td class="text-end text-warning fw-bold font-monospace">
                                    <?= number_format($log['prompt_tokens']); ?>
                                </td>
                                <td class="text-end pe-4 text-success fw-bold font-monospace">+
                                    <?= number_format($log['completion_tokens']); ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="card shadow-sm border-0 border-top border-info border-4 rounded-3 h-100 mb-5">
    <div
        class="card-header bg-white border-bottom-0 pb-0 pt-4 px-4 d-flex justify-content-between align-items-center mb-2">
        <h4 class="mb-0 text-dark fw-bold">Live Outbound Messaging Logs</h4>
        <div class="badge bg-info text-dark p-2 border border-info shadow-sm"><i class="bi bi-broadcast pe-1"></i>
            Cellular</div>
    </div>

    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="bg-light text-secondary small" style="border-top: 2px solid #eaeaea;">
                    <tr>
                        <th class="ps-4 py-3">TIMESTAMP</th>
                        <th class="py-3">INITIATOR</th>
                        <th class="py-3">DESTINATION</th>
                        <th class="py-3">VECTOR</th>
                        <th class="text-end pe-4 py-3">SERVER RESPONSE</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($data['msg_logs'])): ?>
                        <tr>
                            <td colspan="5" class="text-center py-5 text-muted">
                                <i class="bi bi-x-circle fs-2 d-block mb-3 text-secondary opacity-25"></i>
                                No SMS or WhatsApp broadcasts have been deployed through the API gateway.
                            </td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($data['msg_logs'] as $log): ?>
                            <tr>
                                <td class="ps-4 font-monospace small text-muted">
                                    <i class="bi bi-clock-history me-1"></i>
                                    <?= date('Y-m-d H:i:s', strtotime($log['created_at'])); ?>
                                </td>
                                <td>
                                    <?php if ($log['full_name']): ?>
                                        <div class="d-flex align-items-center">
                                            <div class="bg-info bg-opacity-10 text-info fw-bold rounded-circle d-flex align-items-center justify-content-center me-2"
                                                style="width: 32px; height: 32px; font-size: 13px;">
                                                <?= strtoupper(substr($log['full_name'], 0, 1)); ?>
                                            </div>
                                            <span class="text-dark fw-bold">
                                                <?= htmlspecialchars($log['full_name']); ?>
                                            </span>
                                        </div>
                                    <?php else: ?>
                                        <span class="text-muted fst-italic">System Core</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <span class="font-monospace fw-bold text-dark">
                                        <?= htmlspecialchars($log['recipient_number']); ?>
                                    </span>
                                </td>
                                <td>
                                    <?php if ($log['gateway'] == 'WhatsApp'): ?>
                                        <span class="badge bg-success bg-opacity-10 text-success border border-success"><i
                                                class="bi bi-whatsapp"></i> WhatsApp</span>
                                    <?php else: ?>
                                        <span class="badge bg-primary bg-opacity-10 text-primary border border-primary"><i
                                                class="bi bi-chat-text-fill"></i> SMS Relay</span>
                                    <?php endif; ?>
                                </td>
                                <td class="text-end pe-4">
                                    <?php if ($log['status'] == 'Sent'): ?>
                                        <span class="text-success fw-bold"><i class="bi bi-check-circle-fill"></i> Delivered</span>
                                    <?php else: ?>
                                        <div class="text-danger fw-bold"><i class="bi bi-exclamation-triangle-fill"></i> Failed
                                        </div>
                                        <?php if ($log['error_message']): ?>
                                            <small class="text-muted fst-italic mt-1 d-block text-truncate" style="max-width:200px;"
                                                title="<?= htmlspecialchars($log['error_message']); ?>"><?= htmlspecialchars($log['error_message']); ?></small>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const runBtn = document.getElementById('btnRunCron');
        const outBox = document.getElementById('cronOutputAlert');

        if (runBtn) {
            runBtn.addEventListener('click', () => {
                if (!confirm("Initating the Automated Engine manually will consume AI Tokens generating Anniversary messages. Proceed?")) return;

                runBtn.disabled = true;
                runBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-1" role="status"></span> Booting Engine...';

                outBox.classList.remove('d-none');
                outBox.classList.remove('alert-dark', 'alert-danger', 'alert-success');
                outBox.classList.add('alert-warning');
                outBox.textContent = "Connecting to Background Service /cron.php...\n";

                fetch('/cron.php?auth=internal_system')
                    .then(response => {
                        if (!response.ok) throw new Error('Systems Check Failed - Unauthorized');
                        return response.text();
                    })
                    .then(text => {
                        outBox.classList.replace('alert-warning', 'alert-success');
                        outBox.textContent += text;
                    })
                    .catch(err => {
                        outBox.classList.replace('alert-warning', 'alert-danger');
                        outBox.textContent += "\nCRITICAL ERROR: " + err.message;
                    })
                    .finally(() => {
                        runBtn.disabled = false;
                        runBtn.innerHTML = '<i class="bi bi-gear-wide-connected me-1"></i> Trigger Scheduled Tasks';
                    });
            });
        }
    });
</script>